import '@/styles/globals.css';
import '@/styles/reset.css';

import clsx from 'clsx';
import { Noto_Sans_KR } from 'next/font/google';
import Image from 'next/image';
import Link from 'next/link';

const NotoSans = Noto_Sans_KR({
  weight: ['200', '400', '600'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Swipe',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className="flex w-screen justify-center bg-[#fff]">
      <body
        className={clsx(
          [NotoSans.className],
          ['min-h-screen w-full max-w-[430px]'],
          ['relative shadow-lg'],
          ['bg-[#050014]'],
          ['text-white'],
        )}
      >
        <header className="min-h-[50px] w-full p-4">
          <Link href="/">
            <Image
              src="/images/nav_logo.png"
              width={140}
              height={40}
              alt="nav_logo"
            />
          </Link>
        </header>
        <main className={`${NotoSans.className} relative w-full`}>
          {children}
        </main>
      </body>
    </html>
  );
}
