import Head from 'next/head';
import styled from 'styled-components';
import { Bagel_Fat_One } from 'next/font/google';

const BagelFatOne = Bagel_Fat_One({
  weight: '400',
  subsets: ['latin'],
});

// TODO: 이 부분은 테스트용으로 작성된 부분입니다. 추후 삭제해야 합니다.
const TestText = styled.p`
  font-weight: 400;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${BagelFatOne.className}`}>
        <TestText>Main Page</TestText>
      </main>
    </>
  );
}
