import '../styles/reset.css';
import '../styles/globals.css';

import clsx from 'clsx';
import { Bagel_Fat_One } from 'next/font/google';
import Link from 'next/link';

const BagelFatOne = Bagel_Fat_One({
  weight: '400',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className="flex w-screen justify-center bg-[#fff]">
      <body
        className={clsx(
          [BagelFatOne.className],
          ['min-h-screen w-full max-w-[430px]'],
          ['shadow-xl'],
          ['bg-[#050014]'],
          ['text-white'],
        )}
      >
        <nav className="w-full py-4">
          <ul className="flex gap-4">
            <li>
              <Link href="/">Main</Link>
            </li>
            <li>
              <Link href="/home">Home</Link>
            </li>
            <li>
              <Link href="/swiping">Swiping</Link>
            </li>
            <li>
              <Link href="/result">Result</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
