import '../styles/reset.css';
import '../styles/globals.css';

import clsx from 'clsx';
import { Bagel_Fat_One } from 'next/font/google';
import Script from 'next/script';

const BagelFatOne = Bagel_Fat_One({
  weight: '400',
  subsets: ['latin'],
  // https://github.com/vercel/next.js/issues/47115
  // ! fix - `Failed to find font override values for font `Bagel Fat One`
  adjustFontFallback: false,
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className="flex w-screen justify-center bg-[#fff]">
      <body
        className={clsx(
          [BagelFatOne.className],
          ['min-h-screen w-full max-w-[430px]'],
          ['shadow-xl'],
          ['bg-[#050014]'],
          ['text-white'],
        )}
      >
        {children}

        <Script
          src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_API_KEY}&libraries=services,clusterer&autoload=false`}
          strategy="beforeInteractive"
        />
        <Script
          src="https://developers.kakao.com/sdk/js/kakao.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
